services:
  - type: web
    name: solscan-monitor
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable